version: '3.1'

services:

  app:
    build: .
    restart: always
    ports:
      - '${PORT}:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db
    # environment:
    #   - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}'
    #   - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - 'ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_ROOT_USERNAME}'
      # - 'ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}'
      # - 'ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}'
    depends_on:
      - mongo