version: '3.1'

services:

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - /app/node_modules
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: notes
    #   MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=notes
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=notes
      # - 'ME_CONFIG_MONGODB_ADMINPASSWORD=123456'
    depends_on:
      - mongo